# Generated by Django 4.2.3 on 2023-07-30 12:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('viedeos', '0004_video_description_video_likes_video_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
