# Generated by Django 4.2.3 on 2023-07-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viedeos', '0006_remove_review_post_review_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_author', to='viedeos.author'),
        ),
    ]
