# Generated by Django 4.2.3 on 2023-07-30 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viedeos', '0007_alter_video_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.ManyToManyField(related_name='video_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
