# Generated by Django 4.2.3 on 2023-07-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viedeos', '0009_video_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
    ]
