# Generated by Django 4.2.3 on 2023-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viedeos', '0010_remove_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
