# Generated by Django 4.2.3 on 2023-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viedeos', '0012_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
